services:

  # =========================================================
  # MYSQL - TEST DATABASE
  # =========================================================

  mysql-test:
    image: mysql:8.4

    container_name: nguongocso-mysql-test

    restart: "no"

    environment:
      MYSQL_ROOT_PASSWORD: root_test_password
      MYSQL_DATABASE: nguon_goc_so_test
      MYSQL_USER: nguongocso_test
      MYSQL_PASSWORD: Dev2026

    ports:
      - "3308:3306"

    volumes:
      - mysql_test_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-proot_test_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:

  mysql_test_data:
    name: nguongocso_mysql_test_data