spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.vn.nguongocso=INFO
#logging.level.root=DEBUG
#logging.level.vn.nguongocso=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.web=DEBUG

app.jwt.secret=${JWT_SECRET:Q29uZmlndXJlACB1cTVyTG9uZ1NlY3JldEtleUZvckpXVDI1NkJpdA==}
app.jwt.expiration=86400000

app.upload.base-dir=./uploads
app.upload.farm-log.relative-path=farm-logs

app.upload.farm-log.max-size=5242880
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

qr.image.storage.path=./files/qr